name: avatar_glow
homepage: https://github.com/apgapg/avatar_glow
description: A Flutter package providing a Avatar Glow Widget with cool background glowing animation
version: 3.0.1
repository: https://github.com/apgapg/avatar_glow
issue_tracker: https://github.com/apgapg/avatar_glow/issues

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1

topics:
  - glow-effect
  - custom-widget
  - ripple-effect
  - sound-wave
  - avatar

screenshots:
  - description: 'Package Demo'
    path: src/app.gif